### ISSUE TITLE
angular.json missing from download

### ISSUE THREAD

**Issue by dziesig** [cornflourblue/angular-6-registration-login-example#5]
I downloaded the zip file, unpacked it and issued "ng serve".
The response was:
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/home/donz/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/home/donz/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (/home/donz/node_modules/@angular/cli/models/architect-command.js:180:32)
    at ServeCommand.<anonymous> (/home/donz/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /home/donz/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/donz/node_modules/@angular/cli/models/architect-command.js:3:12)
    at ServeCommand.initialize (/home/donz/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/home/donz/node_modules/@angular/cli/models/command-runner.js:87:23)
I am using:
 Angular CLI: 6.0.7
Node: 8.11.2
OS: linux x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cli                      6.0.7
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
    
Am I missing something?

Thanks,
Don

**Comment by dziesig** [comment]
I missed the line "npm install" before running the app.  It works fine now.  Sorry about false alarm.
Don

**Comment by nikolasamardzija** [comment]
@dziesig Hi, I have the same problem. I go to the project location and do npm install (also tried with sudo npm install -g @angular/cli) and after that ng serve --open and have same error as you. I'm really new to this, so pardon this basic question :)
angular-6-registration-login-example nikolasamardzija$ ng serve --open
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:180:32)
    at ServeCommand.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:3:12)
    at ServeCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:87:23)
