### ISSUE TITLE
Unable to run the app using ng serve

### ISSUE THREAD

**Issue by pasumarthivijaykumar** [cornflourblue/angular-6-registration-login-example#7]
Getting below error, can you please let me know what needs to be done from configuration.
i have npm version 
$ npm -version
6.2.0

$ ng serve --port 4203
**Local workspace file ('angular.json') could not be found.**
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (F:\angularWorkspace\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (F:\angularWorkspace\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (F:\angularWorkspace\node_modules\@angular\cli\models\architect-command.js:180:32)
    at ServeCommand.<anonymous> (F:\angularWorkspace\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at F:\angularWorkspace\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (F:\angularWorkspace\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (F:\angularWorkspace\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (F:\angularWorkspace\node_modules\@angular\cli\models\command-runner.js:87:23)

**Comment by faizal100ip** [comment]
same issues 'Local workspace file ('angular.json') could not be found.'

**Comment by emilioparodi** [comment]
Same problem, solved with:

npm install -g @angular/cli 

npm start

**Comment by cornflourblue** [comment]
This version of the project uses webpack not angular cli, the angular cli version is at https://github.com/cornflourblue/angular-6-registration-login-example-cli
